version: "3.3"
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    restart: "unless-stopped"
    networks:
      - backend
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.prod
    expose:
      - "80"  # Expose port 80 internally
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    
 
networks:
  backend:
    driver: bridge
  